### ISSUE TITLE
Cannot convert to arf file without timestamps.npy file 

### ISSUE THREAD

**Issue by SMMoseley** [melizalab/arfx#28]
The folder is called C194_2023-10-16_16-30-54_chorus on grafisia

arfx-oephys -T EXTRAC_HP -k experimenter=smm3rc -k bird=C194 -k pen=1 -k site=1 -k protocol=chorus -f C194_1_1.arf C194_2023-10-16_16-30-54_chorus/

[arfx-oephys] Opened 'C194_1_1.arf' for writing
[arfx-oephys] Reading from 'C194_2023-10-16_16-30-54_chorus/Record Node 104/experiment1/recording1':
[arfx-oephys] - warning: timestamps.npy file is missing for Rhythm_FPGA-100.0; falling back on sync_messages.txt
Traceback (most recent call last):
  File "/home/melizalab/.local/pipx/venvs/arfx/lib/python3.8/site-packages/arfx/oephys.py", line 48, in __init__
    timestamps = np.load(
  File "/home/melizalab/.local/pipx/venvs/arfx/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'C194_2023-10-16_16-30-54_chorus/Record Node 104/experiment1/recording1/continuous/Rhythm_FPGA-100.0/timestamps.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/melizalab/.local/bin/arfx-oephys", line 8, in <module>
    sys.exit(script())
  File "/home/melizalab/.local/pipx/venvs/arfx/lib/python3.8/site-packages/arfx/oephys.py", line 323, in script
    rec = recording(dir)
  File "/home/melizalab/.local/pipx/venvs/arfx/lib/python3.8/site-packages/arfx/oephys.py", line 171, in __init__
    dset = continuous_dset(path, processor)
  File "/home/melizalab/.local/pipx/venvs/arfx/lib/python3.8/site-packages/arfx/oephys.py", line 64, in __init__
    raise RuntimeError(
RuntimeError: unable to determine sync time for Rhythm_FPGA-100.0 dataset

**Comment by dmeliza** [comment]
This should have been fixed with issue #27. However, it appears the `sync_messages.txt` file that the script falls back on is empty for these recordings. Not sure why this is, but without it, there's no way to recover the information that was in `timestamps.npy`.
